vocab_size: 50257
decoder_embed_dim: 2048
decoder_layers: 24
decoder_retention_heads: 8
decoder_ffn_embed_dim: 4096
initializer_range: 0.02
output_retentions: False
pad_token_id: 50256
eos_token_id: 50256
unk_token_id: 50256
