vocab_size: 50257
decoder_embed_dim: 1024
decoder_layers: 16
decoder_retention_heads: 4
decoder_ffn_embed_dim: 2048
initializer_range: 0.02
output_retentions: False
pad_token_id: 50256
eos_token_id: 50256
unk_token_id: 50256
