vocab_size: 50257
decoder_embed_dim: 4096
decoder_layers: 32
decoder_retention_heads: 16
decoder_ffn_embed_dim: 8192
initializer_range: 0.02
output_retentions: False
pad_token_id: 50256
eos_token_id: 50256
unk_token_id: 50256
